title: twitty.dev(log)
description: daily specials from the dev kitchen
baseurl: "/blog"
url: "" # will be set by GitHub Pages

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-feed
