title: twitty.dev(log)
description: daily specials from the dev kitchen
baseurl: ""
url: "https://twitty.dev"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-feed
